fixed paths for staticDir on windows which returned 400 bad request.
dom96/jester pull request #260
Opened 2020-08-25 23:58 UTC by alopez1121

I was running jester on windows and couldn't get static files to be served without incurring a 400 bad request. After digging around the source I found that the comparison on line 318 of the original source `if pathDir.startsWith(staticDir)` would return false because of a trailing slash.
Example:

`pathDir = "%somepath%/client/build"`
`staticDir = "%somepath%/client/build/"`

 After changing the way the pathDir prevents directory traversal and ensuring that the staticDir is always without a trailing slash, it works on windows.

I wanted to test using `nimble test` but unfortunately they are unable to run due to a combination of out of date async libraries `PCustomOverlap -> CustomRef` and the inability to run the asyncdispatcher server which I didn't look into.

I was hoping you could review and comment on any concerns with the changes.

2020-08-26 20:29 UTC, dom96 requested changes

2020-08-26 20:29 UTC, dom96 commented on jester.nim
> +  let pathDir = path.replace("..", "") / ""
I'm not sure about this change. Based on what you're saying in the description it seems that this change should require a simple removal of a trailing slash somewhere, wouldn't that work?

2020-08-26 23:38 UTC, alopez1121 commented on jester.nim
> +  let pathDir = path.replace("..", "") / ""
This is my first time really using github to contribute to open source so thank you for being patient.

I have the problem worked out now I think. 

Testing method:
1. create a static directory, mine was `${somePath}/client/build` and place an index.html
2. run jester with that static directory set
3. navigate to localhost:<port>
4. [Windows] you get 400 Bad Request.

Observation:
The printout of `pathDir` after the call to `path.splitFile.dir / ""`  would yield `${somePath}/client`, this is because splitFile interprets a path that ends without a trailing slash as pointing to a file not a directory.

I noticed that `let path = normalizedPath(staticPath / cgi.decodeUrl)` would yield a path without a trailing slash, for all paths that are not simply "/". which would lead the `path.splitFile.dir` call to "eat" the last directory by interpreting it as a file instead of a directory.

This would then fail when testing `if pathDir.startsWith(staticDir)`, because `pathDir == fmt"{somePath}/client" and staticDir == fmt"{somePath}/client/build"` resulting in 400 Bad Request.

Changes:

I normalize the staticPath once on `proc newSettings`. Then I normalize *only* `cgi.decodeUrl(req.pathInfo)` like so: `let path = jes.settings.staticDir / normalizedPath(cgi.decodeUrl(req.pathInfo))` this way when `req.pathInfo == "/"` it simply tacks on the trailing slash which then allows the `path.splitFile.dir` call to match the public directory (assuming it is *supposed* match of course).

I forced the changes to my repo in the staticDir-windows branch do I issue you a new pull request or is this one amenable?

2020-08-27 19:47 UTC, dom96 approved these changes
Much simpler and nicer. Thanks!

2020-08-27 19:47 UTC, merged