Specify number of threads to be used by httpbeast
dom96/jester pull request #285
Opened 2021-11-16 10:02 UTC by ThomasTJdev

This PR adds a new setting to specify the number threads when compiled with `useHttpBeast`.

Solves #233 and allows the user to define the number of threads `httpBeast` may use when it is initiated from within `jester`.

**Example**
```nim
# specify_threads.nim
import jester

settings:
  bindAddr    = "127.0.0.1"
  port        = Port(5040)
  numThreads  = 3

routes:
  get "/":
    resp "threads"
```
```bash
$ nim c -r specify_threads.nim
INFO Jester is making jokes at http://127.0.0.1:5040
Starting 3 threads
Listening on port 5040
```

2021-11-23 00:08 UTC, dom96 requested changes

2021-11-23 00:08 UTC, dom96 commented on jester/private/utils.nim
> +      numThreads*: int
hm, might be a bit annoying to have this fail on Windows when it's specified. Maybe just remove the `when` and add a note?

2021-11-30 16:03 UTC, ThomasTJdev commented on jester/private/utils.nim
> +      numThreads*: int
Of course - new proposal committed!

2021-11-30 20:09 UTC, dom96 approved these changes
Thanks!

2021-11-30 20:10 UTC, merged